### ISSUE TITLE
question sur formalisme

### ISSUE THREAD

**Issue by jpierre03** [Taeradan/Caronch#2]
Bonjour,

En utilisant Caronch pour modéliser un processus j'ai souhaité ajouter de la lisibilité en distinguant les données issues d'un process.

Questions :
- est-ce conforme au formalisme ? Aucune des 7 règles ne l'indique.
- quelle stratégie adopter ?

Pour plus de clarté, 2 schémas.

Diag 1: fonctionnement avec un seul type de donnée en sortie

![question_raw](https://cloud.githubusercontent.com/assets/954536/10428510/3f8cde92-70f2-11e5-8adb-1f85ccfef537.png)

Diag 2: fonctionnement avec plusieurs types de données en sortie

![question](https://cloud.githubusercontent.com/assets/954536/10428526/616548e2-70f2-11e5-9ad5-4688488af455.png)

**Comment by Taeradan** [comment]
Après discussion, les prédicats sont acceptés. Il faut préciser dans la définition du formalisme quels sont els types de données acceptés.
